# GraphQLスキーマの定義
type User {
  id: ID
  name: String
  email: String
}

input UserInput {
  name: String!
  email: String!
}

type Query {
  users: [User!]!
  hello: String!
}

type Mutation {
  createUser(input: UserInput): [User!]!
}
